---
title: "心理統計教育教材"
---

専修大学人間科学部心理学科では、「心理学データ解析基礎」を1年次の必修科目とし、「心理学データ解析応用」を2年次の選択科目としています。
このサイトではこれらの授業に準拠した、授業の進行方針文書と、それに対応した心理学の統計学習に関する教材を提供しています。

## シラバスの設計方針

### 基礎編

「統計学」よりも「心理統計学」の視点を重視し、その実践的な使い方や、心理学におけるその役割と前提条件を理解できるように心掛けています。

また、公認心理師の資格取得に対応した内容であり、どの部分がどの要素につながるか理解できるようにしています。

1年間を通じて、以下の5つのテーマに焦点を当てています。

- **推測統計を用いた母集団の理解** 統計学や心理統計学では、単にサンプルから得られたデータを分析するだけでなく、それを用いて母集団全体を理解することが目的です。
- **確率を使った推論** 母集団を理解するための方法として、代表値に基づくモーメント法、確率分布を使用した最尤法、そしてベイズ法があります。
- **要因設計と線形モデル** 心理学では、要因設計により実験条件をコントロールし、平均値の違いを基に分析（平均因果効果）を行うことが多い。この過程は全体として線形モデルによって表現可能です。
- **モデル比較と意思決定** 母集団の推定だけでなく、それを基にした「結論」や「意思決定」を行うためには、モデル比較やNHST（Null Hypothesis Statistical Testing）などの方法が必要です。
- **Rを用いた実践的な学習** 統計ソフトRを使い、理論的な理解だけでなく、自分自身で計算できるスキルも身につけるべきです。

### 応用編

「データ解析基礎」では記述統計と推測統計を学びました。また基礎実験の授業で実際に統計法を使ったレポートも書いていると思います。しかし使い始めると、基礎でわかっていなかったことに気づき始めるのではないでしょうか。この授業は「基礎で学んだ理論」と「基礎実験で行う実践」の間をつなぐ知識を補填します。そのための数学的・実践的技術として、線形代数とプログラミングを中心におきます。

データ解析応用1（前期）では、次の3点に焦点化しています。

- **尺度化の理解** 心理学のアンケートや分析が「心を測定する」ものとしてどのように機能するのか、その原理とモデルを理解し活用できるようにする。
- **多変量解析の理解** 調査研究などから得られた多くの変量を分析することで何が分かるのか、またそれをどう解釈するかを理解する。
- **数学的一貫性の理解** 多変量解析の背後にある数学の原理、特に線形代数を理解することで、多変量解析のメカニズムを統合的に理解する。

データ解析応用2（後期）では、次の3点に焦点化しています。

- **データ生成メカニズムの理解** データを受動的に分析するのではなく、データ生成のメカニズムを理解し、それに基づいて分析を行う能力を養う。
- **シミュレーションによる統計モデルの実践的理解** 統計ソフトRを用いた数値シミュレーションによって、統計モデルの理解を深める。
- **確率的プログラミング言語Stanによるベイジアンモデリング** 確率型プログラミング言語Stanを用いたベイズ推論と、それに基づくモデリングの技法を知る。


## バージョン情報

これらの資料は定期的に更新されます。各ページの左上にあるバージョン情報、または最初のページにある最終更新日時をチェックしてください。バージョン情報は[セマンティックバージョニング 2.0](https://semver.org/lang/ja/)に従っています。

| 資料 | 最新バージョン |
|------|--------------|
| 基礎シラバス | 3.0.1 |
| 基礎テキスト | 3.29.0 |
| 応用シラバス2A | 2.0.12 |
| 応用シラバス2B | 2.0.12 |
| 応用テキスト | 2.0.6 |

## 関連コンテンツ

- [心理学統計実習](https://kosugitti.github.io/PsyStatsPracticals/) --- Rの基礎からベイジアンモデリングまで網羅したオンラインテキスト
- [Rドリル](https://kosugitti.github.io/kosugi-labo/r-tutorial/index.html) --- ゼミ生向けRプログラミング課題（一般にも公開）
